In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/205e1808-6-dataset/data.csv')
print(dataset.shape)


(45200, 10)


In [ ]:
 dataset['datetime'] = pd.to_datetime(dataset['datetime'])

 dataset['hour'] = dataset['datetime'].dt.hour
dataset['day_of_week'] = dataset['datetime'].dt.dayofweek
print(dataset.shape)

 X = dataset.iloc[:, [2, 3, 4, 5, 6,7,8, 10, 11]].values
y = dataset.iloc[:, [9]].values
print(X.shape)

(45200, 12)
(45200, 9)


In [ ]:
 X_columns = dataset.iloc[:, [2, 3, 4, 5, 6, 7, 8, 10, 11]].columns
print(X_columns)
yy = dataset.iloc[:, [9]].columns
print(yy)

Index(['siteid', 'offerid', 'category', 'merchant', 'countrycode', 'browserid',
       'devid', 'hour', 'day_of_week'],
      dtype='object')
Index(['click'], dtype='object')


In [ ]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
X[:, [5, 6]] = imputer.fit_transform(X[:, [5, 6]])
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='constant', fill_value=-1)
X[:, [0]] = imputer.fit_transform(X[:, [0]])



In [ ]:
categorical_columns = [4, 5, 6, 7, 8]

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

for column in categorical_columns:
    X[:, column] = label_encoder.fit_transform(X[:, column])

print(X)



[[6310005.0 99217 41706 ... 1 19 2]
 [-1 287164 89522 ... 2 15 5]
 [2463708.0 948989 12052 ... 1 10 4]
 ...
 [2656998.0 324233 48430 ... 1 21 6]
 [-1 908599 904 ... 2 7 0]
 [9223301.0 487571 41640 ... 1 13 1]]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [ ]:
# sd

ID                0
datetime          0
siteid         4518
offerid           0
category          0
merchant          0
countrycode       0
browserid      2345
devid          6864
click             0
hour              0
day_of_week       0
dtype: int64


apply the model here
**bold text**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred  = classifier.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)

print(f'Accuracy: {accuracy}')

Accuracy: 0.8571902654867256


In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[4421  664]
 [ 627 3328]]


In [ ]:
from sklearn.metrics import f1_score
f1 = f1_score(y_test, y_pred)

print(f"F1 Score: {f1}")

F1 Score: 0.837548760538568


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

# Print the number of "1"s and "0"s in training data
print("Training Data:")
print("Number of '1's:", sum(y_train == 1))
print("Number of '0's:", sum(y_train == 0))

# Print the number of "1"s and "0"s in testing data
print("\nTesting Data:")
print("Number of '1's:", sum(y_test == 1))
print("Number of '0's:", sum(y_test == 0))


# Calculate and print the confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(conf_matrix)

# Calculate accuracy for each class
accuracy_0 = conf_matrix[0, 0] / sum(conf_matrix[0, :])
accuracy_1 = conf_matrix[1, 1] / sum(conf_matrix[1, :])

# Print accuracy for each class
print("\nAccuracy for '0':", accuracy_0)
print("Accuracy for '1':", accuracy_1)


Training Data:
Number of '1's: [16045]
Number of '0's: [20115]

Testing Data:
Number of '1's: [3955]
Number of '0's: [5085]

Confusion Matrix:
[[4421  664]
 [ 627 3328]]

Accuracy for '0': 0.8694198623402163
Accuracy for '1': 0.8414664981036662
